basePath: /
definitions:
  api.CrawlResponse:
    properties:
      end:
        type: integer
      page:
        type: integer
      start:
        type: integer
      status:
        type: string
    type: object
  api.actorPayload:
    properties:
      name:
        type: string
    type: object
  store.Actor:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  store.Video:
    properties:
      actor:
        items:
          type: string
        type: array
      category:
        type: string
      created_at:
        type: string
      description:
        type: string
      director:
        items:
          type: string
        type: array
      id:
        type: integer
      link_embed:
        type: string
      name:
        type: string
      origin_name:
        type: string
      poster_url:
        type: string
      slug:
        type: string
      studio:
        items:
          type: string
        type: array
      tag:
        items:
          type: string
        type: array
      thumb_url:
        type: string
      updated_at:
        type: string
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: AVDB crawler and API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Go - AVDB
paths:
  /actor:
    get:
      consumes:
      - application/json
      description: Get actor list
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/store.Actor'
            type: array
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get actor list
      tags:
      - actor
    post:
      consumes:
      - application/json
      description: Create actor
      parameters:
      - description: Actor request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api.actorPayload'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/store.Actor'
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Create actor
      tags:
      - actor
  /actor/{id}:
    delete:
      consumes:
      - application/json
      description: Delete actor
      parameters:
      - description: Actor ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Delete actor
      tags:
      - actor
    put:
      consumes:
      - application/json
      description: Update actor
      parameters:
      - description: Actor ID
        in: path
        name: id
        required: true
        type: integer
      - description: Actor request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api.actorPayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/store.Actor'
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Update actor
      tags:
      - actor
  /crawl/{page}:
    get:
      description: Crawl single page asynchronously
      parameters:
      - description: Page number
        in: path
        name: page
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/api.CrawlResponse'
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Crawl page
      tags:
      - crawler
  /crawl/all:
    get:
      description: Crawl all pages asynchronously
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/api.CrawlResponse'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Crawl all
      tags:
      - crawler
  /crawl/range:
    get:
      description: Crawl range of pages asynchronously
      parameters:
      - description: Start page
        in: query
        name: start
        required: true
        type: integer
      - description: End page
        in: query
        name: end
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/api.CrawlResponse'
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Crawl range
      tags:
      - crawler
  /video/{slug}:
    get:
      consumes:
      - application/json
      description: Get video detail by slug
      parameters:
      - description: Video slug
        in: path
        name: slug
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/store.Video'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get video detail by slug
      tags:
      - video
swagger: "2.0"
